version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_logBook
    environment:
      POSTGRES_DB: logBook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
