export const DISPLAY_ALERT: string = "DISPLAY_ALERT";
export const CLEAR_ALERT: string = "CLEAR_ALERT";
export const SETUP_USER_BEGIN: string = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS: string = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR: string = "SETUP_USER_ERROR";
export const LOGOUT_USER: string = "LOGOUT_USER";
export const GET_MUSCLES_BEGIN: string = "GET_MUSCLES_BEGIN";
export const GET_MUSCLES_SUCCESS: string = "GET_MUSCLES_SUCCESS";
export const GET_MUSCLES_ERROR: string = "GET_MUSCLES_ERROR";
export const GET_WORKOUTS_BY_MUSCLE_BEGIN: string =
  "GET_WORKOUTS_BY_MUSCLE_BEGIN";
export const GET_WORKOUTS_BY_MUSCLE_SUCCESS: string =
  "GET_WORKOUTS_BY_MUSCLE_SUCCESS";
export const GET_WORKOUTS_BY_MUSCLE_ERROR: string =
  "GET_WORKOUTS_BY_MUSCLE_ERROR";
export const ADD_WORKOUT_BEGIN = "ADD_WORKOUT_BEGIN";
export const ADD_WORKOUT_SUCCESS = "ADD_WORKOUT_SUCCESS";
export const ADD_WORKOUT_ERROR = "ADD_WORKOUT_ERROR";
